name: Bug Report
description: Report a bug in OpenTelemetry Helm Charts
title: "[Bug]: "
labels: ["bug", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us investigate and resolve the issue.

  - type: input
    id: chart_name
    attributes:
      label: Chart Name
      description: Which chart is affected?
      placeholder: e.g., opentelemetry-collector, opentelemetry-operator, opentelemetry-demo
    validations:
      required: true

  - type: input
    id: chart_version
    attributes:
      label: Chart Version
      description: What version of the chart are you using?
      placeholder: e.g., 0.45.0
    validations:
      required: true

  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Tell us what you expected to see!
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Deploy chart with values...
        2. Check status...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide details about your environment
      placeholder: |
        - Kubernetes version: [e.g., 1.24.0]
        - Helm version: [e.g., 3.10.0]
        - Operating System: [e.g., Ubuntu 20.04]
        - Platform: [e.g., EKS, GKE, minikube]
    validations:
      required: true

  - type: textarea
    id: helm_values
    attributes:
      label: Helm Values
      description: Relevant Helm values used (please remove sensitive information)
      render: yaml
      placeholder: |
        config:
          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any additional information you think may be relevant to this issue.

  - type: dropdown
    attributes:
      label: Tip
      description: This element is static, used to render a helpful sub-heading for end-users and community members to help prioritize issues. Please leave as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0