name: New Chart Request
description: Request a new Helm chart for OpenTelemetry
title: "[New Chart]: "
labels: ["new chart", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new chart! Please provide as much detail as possible to help us understand your request.

  - type: input
    id: chart_name
    attributes:
      label: Proposed Chart Name
      description: What would you like to name the new chart?
      placeholder: e.g., opentelemetry-jaeger, opentelemetry-prometheus
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Chart Description
      description: A clear and concise description of what this chart would do.
      placeholder: This chart would deploy and configure...
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe the use case for this chart. Why is it needed?
      placeholder: This chart would be useful for...
    validations:
      required: true

  - type: textarea
    id: components
    attributes:
      label: Components
      description: What OpenTelemetry or related components would this chart include?
      placeholder: |
        - OpenTelemetry Collector
        - Jaeger
        - Prometheus
        - etc.
    validations:
      required: true

  - type: textarea
    id: existing_solutions
    attributes:
      label: Existing Solutions
      description: Are there existing Helm charts or deployment methods for these components? How would this chart be different?
      placeholder: There are existing charts for X, but they don't...

  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: What are the key requirements for this chart?
      placeholder: |
        - Must support configuration of...
        - Should be compatible with...
        - Needs to handle...

  - type: textarea
    id: resources
    attributes:
      label: Resources
      description: Do you have any resources, documentation, or examples that could help with implementing this chart?
      placeholder: |
        - Official documentation: https://...
        - Example configurations: https://...
        - Related projects: https://...

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any additional information you think may be relevant to this chart request.

  - type: dropdown
    attributes:
      label: Tip
      description: This element is static, used to render a helpful sub-heading for end-users and community members to help prioritize issues. Please leave as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0